# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'FlashDating' do
pod "AFNetworking", "~> 2.0"
pod 'Parse'
pod 'SVProgressHUD'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

end

